Table Operator {
  OperatorID int [pk, increment] // Primary Key
  Nama varchar
  Username varchar
  Password varchar
  TanggalBergabung date
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table Gudang {
  GudangID int [pk, increment] // Primary Key
  NamaGudang varchar
  Lokasi varchar
  Deskripsi varchar // Deskripsi tentang gudang
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
 Status enum('draft', 'active', 'deleted') // Status record
}

Table Kategori {
  KategoriID int [pk, increment] // Primary Key
  NamaKategori varchar
  Deskripsi varchar // Deskripsi tentang kategori
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table Barang {
  BarangID int [pk, increment] // Primary Key
  SKU varchar // Stock Keeping Unit
  Barcode varchar // Kode batang
  NamaBarang varchar // Nama barang
  Stok int // Jumlah stok yang tersedia
  GudangID int [ref: > Gudang.GudangID] // Foreign Key
  KategoriID int [ref: > Kategori.KategoriID] // Foreign Key
  Deskripsi varchar // Deskripsi tentang barang
  Berat decimal // Berat barang
  Dimensi varchar // Dimensi barang (misalnya, "10x5x2 cm")
  Gambar varchar // URL atau path ke gambar barang
  StatusBarang enum('active', 'inactive', 'discontinue') // Status barang
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table KategoriSatuan {
  KategoriSatuanID int [pk, increment] // Primary Key
  NamaKategori varchar // Nama kategori satuan (misalnya, "berat", "volume")
  Deskripsi varchar // Deskripsi tentang kategori satuan
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table Satuan {
  SatuanID int [pk, increment] // Primary Key
  NamaSatuan varchar // Nama satuan
  Deskripsi varchar // Deskripsi tentang satuan
  Urutan int // Urutan satuan
  KategoriSatuanID int [ref: > KategoriSatuan.KategoriSatuanID] // Foreign Key
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table BarangSatuan {
  BarangSatuanID int [pk, increment] // Primary Key
  BarangID int [ref: > Barang.BarangID] // Foreign Key
  SatuanID int [ref: > Satuan.SatuanID] // Foreign Key
  Konversi decimal // Misalnya, jumlah dalam satuan dasar
  HargaBeli decimal // Harga beli untuk satuan ini
  HargaJual decimal // Harga jual untuk satuan ini
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table Transaksi {
  TransaksiID int [pk, increment] // Primary Key
  TanggalTransaksi date
  OperatorID int // Foreign Key
  TotalHarga decimal
  JenisTransaksi enum('jusl', 'beli', 'mutasi') // Jenis transaksi
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table DetailTransaksi {
  DetailTransaksiID int [pk, increment] // Primary Key
  TransaksiID int [ref: > Transaksi.TransaksiID] // Foreign Key
  BarangID int [ref: > Barang.BarangID] // Foreign Key
  SatuanID int [ref: > Satuan.SatuanID] // Foreign Key
  Jumlah int
  Subtotal decimal
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table RiwayatStock {
  RiwayatStockID int [pk, increment] // Primary Key
  BarangID int [ref: > Barang.BarangID] // Foreign Key
  Tanggal datetime // Tanggal perubahan stok
  JumlahPerubahan int // Jumlah perubahan stok (positif/negatif)
  Keterangan varchar // Keterangan tentang perubahan stok
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table MetodePembayaran {
  MetodePembayaranID int [pk, increment] // Primary Key
  NamaMetode varchar // Nama metode pembayaran
  Deskripsi varchar // Deskripsi tentang metode pembayaran
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table Pembayaran {
  PembayaranID int [pk, increment] // Primary Key
  TransaksiID int [ref: > Transaksi.TransaksiID] // Foreign Key
  MetodePembayaranID int [ref: > MetodePembayaran.MetodePembayaranID] // Foreign Key
  Jumlah decimal // Jumlah yang dibayarkan
  TanggalPembayaran datetime // Tanggal pembayaran dilakukan
  Keterangan varchar // Keterangan tambahan
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'completed', 'failed') // Status pembayaran
}

Table Pelanggan {
  PelangganID int [pk, increment] // Primary Key
  NamaPelanggan varchar // Nama pelanggan
  Alamat varchar // Alamat pelanggan
  Kontak varchar // Kontak pelanggan
  Deskripsi varchar // Deskripsi tentang pelanggan
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table PengembalianBarang {
  PengembalianID int [pk, increment] // Primary Key
  TransaksiID int [ref: > Transaksi.TransaksiID] // Foreign Key
  BarangID int [ref: > Barang.BarangID] // Foreign Key
  Jumlah int // Jumlah barang yang dikembalikan
  Alasan varchar // Alasan pengembalian
  TanggalPengembalian datetime // Tanggal pengembalian
  StatusPengembalian enum('pending', 'completed', 'rejected') // Status pengembalian
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table Notification {
  NotificationID int [pk, increment] // Primary Key
  UserID int // ID pengguna yang menerima notifikasi
  Pesan varchar // Isi notifikasi
  Tanggal datetime // Tanggal notifikasi dibuat
  StatusNotification enum('unread', 'read') // Status notifikasi
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table ActivityLog {
  ActivityLogID int [pk, increment] // Primary Key
  UserID int // ID pengguna yang melakukan aktivitas
  Aktivitas varchar // Deskripsi aktivitas
  Tanggal datetime // Tanggal aktivitas dilakukan
}

Table Role {
  RoleID int [pk, increment] // Primary Key
  NamaRole varchar // Nama peran
  Deskripsi varchar // Deskripsi tentang peran
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table OperatorRole {
  OperatorRoleID int [pk, increment] // Primary Key
  OperatorID int // Foreign Key
  RoleID int [ref: > Role.RoleID] // Foreign Key
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table HakAkses {
  HakAksesID int [pk, increment] // Primary Key
  NamaHakAkses varchar // Nama hak akses (misalnya, "view_barang", "edit_barang")
  Deskripsi varchar // Deskripsi tentang hak akses
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table RoleHakAkses {
  RoleHakAksesID int [pk, increment] // Primary Key
  RoleID int [ref: > Role.RoleID] // Foreign Key
  HakAksesID int [ref: > HakAkses.HakAksesID] // Foreign Key
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table Akun {
  AkunID int [pk, increment] // Primary Key
  NamaAkun varchar // Nama akun (misalnya, "Kas", "Piutang", "Utang", "Pendapatan", "Beban")
  Tipe enum('aktiva', 'pasiva', 'pendapatan', 'beban') // Tipe akun
  Deskripsi varchar // Deskripsi tentang akun
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table Jurnal {
  JurnalID int [pk, increment] // Primary Key
  Tanggal datetime // Tanggal transaksi
  AkunID int [ref: > Akun.AkunID] // Foreign Key
  Deskripsi varchar // Deskripsi transaksi
  Debit decimal // Jumlah debit
  Kredit decimal // Jumlah kredit
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table LaporanKeuangan {
  LaporanID int [pk, increment] // Primary Key
  TanggalMulai date // Tanggal awal periode laporan
  TanggalAkhir date // Tanggal akhir periode laporan
  TotalAktiva decimal // Total aktiva
  TotalPasiva decimal // Total pasiva
  LabaRugi decimal // Total laba atau rugi
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table Diskon {
  DiskonID int [pk, increment] // Primary Key
  NamaDiskon varchar // Nama diskon
  Persentase decimal // Persentase diskon
  NilaiNominal decimal // Nilai nominal diskon (hanya digunakan jika tipe adalah 'nominal')
  Tipe enum('persentase', 'nominal') // Tipe diskon
  Keterangan varchar // Keterangan tentang diskon
  TanggalMulai date // Tanggal mulai diskon berlaku
  TanggalAkhir date // Tanggal akhir diskon berlaku
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

Table DiskonBarang {
  DiskonBarangID int [pk, increment] // Primary Key
  DiskonID int [ref: > Diskon.DiskonID] // Foreign Key
  BarangID int [ref: > Barang.BarangID] // Foreign Key
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

// Tabel ini digunakan untuk mengelola program loyalitas pelanggan.
Table CustomerLoyalty {
  LoyaltyID int [pk, increment] // Primary Key
  PelangganID int [ref: > Pelanggan.PelangganID] // Foreign Key
  Poin int // Jumlah poin yang diperoleh
  TanggalDiterima datetime // Tanggal poin diterima
  Keterangan varchar // Keterangan tambahan
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}

// Tabel ini digunakan untuk menyimpan pengaturan aplikasi, seperti pajak, mata uang, dan preferensi lainnya.
Table Pengaturan {
  PengaturanID int [pk, increment] // Primary Key
  NamaPengaturan varchar // Nama pengaturan
  Nilai varchar // Nilai pengaturan
  Deskripsi varchar // Deskripsi tentang pengaturan
  CreatedAt datetime // Waktu saat record dibuat
  UpdatedAt datetime // Waktu saat record diperbarui
  CreatedBy int // ID operator yang membuat record
  ModifiedBy int // ID operator yang memodifikasi record
  Status enum('draft', 'active', 'deleted') // Status record
}